\set ON_ERROR_STOP on
SELECT version();
SET TIME ZONE 'Asia/Shanghai';

DO $$ BEGIN
  IF (''::text IS NULL) OR NOT (NULLIF('', '') IS NULL) THEN
    RAISE EXCEPTION 'empty string/null semantics changed';
  END IF;
  RAISE NOTICE 'PASS 1: PostgreSQL distinguishes empty text from NULL; explicit NULLIF normalizes it';
END $$;

DO $$ BEGIN
  IF '123.456'::numeric(10,2) <> 123.46 THEN
    RAISE EXCEPTION 'scale conversion did not round as expected';
  END IF;
  BEGIN
    PERFORM '999.995'::numeric(5,2);
    RAISE EXCEPTION 'expected numeric overflow';
  EXCEPTION WHEN numeric_value_out_of_range THEN NULL;
  END;
  RAISE NOTICE 'PASS 2: numeric scale rounds; rounding can then overflow declared precision';
END $$;

DO $$ BEGIN
  IF timestamp '2026-09-10 13:45:30'::date <> date '2026-09-10' THEN
    RAISE EXCEPTION 'date cast mismatch';
  END IF;
  IF timestamptz '2026-09-10 13:45:30+08'
      <> timestamptz '2026-09-10 05:45:30+00' THEN
    RAISE EXCEPTION 'same instant mismatch';
  END IF;
  IF (timestamptz '2026-09-10 13:45:30+08' AT TIME ZONE 'UTC')
      <> timestamp '2026-09-10 05:45:30' THEN
    RAISE EXCEPTION 'UTC conversion mismatch';
  END IF;
  RAISE NOTICE 'PASS 3: date drops time; offset timestamps can identify the same instant';
END $$;

CREATE TEMP TABLE sequence_sample (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label text NOT NULL
);
INSERT INTO sequence_sample(id, label) VALUES (1, 'imported');
DO $$ DECLARE generated_id bigint; BEGIN
  BEGIN
    INSERT INTO sequence_sample(label) VALUES ('default insert before alignment');
    RAISE EXCEPTION 'expected duplicate imported id';
  EXCEPTION WHEN unique_violation THEN NULL;
  END;
  -- Only valid here: isolated nonempty table, positive increment, no other writers.
  PERFORM setval(pg_get_serial_sequence('sequence_sample', 'id'),
      (SELECT max(id) FROM sequence_sample), true);
  INSERT INTO sequence_sample(label) VALUES ('after alignment') RETURNING id INTO generated_id;
  IF generated_id <> 2 THEN RAISE EXCEPTION 'sequence alignment failed'; END IF;
  RAISE NOTICE 'PASS 4: explicit identity import did not advance sequence; isolated alignment restored next id';
END $$;

CREATE TEMP TABLE operation_sample (
  actor_id text NOT NULL,
  operation_id text NOT NULL,
  parameter_hash text NOT NULL,
  PRIMARY KEY(actor_id, operation_id)
);
INSERT INTO operation_sample VALUES ('A', 'op-1', 'hash-1');
DO $$ DECLARE inserted_count integer; saved_hash text; BEGIN
  INSERT INTO operation_sample VALUES ('A', 'op-1', 'hash-2')
    ON CONFLICT (actor_id, operation_id) DO NOTHING;
  GET DIAGNOSTICS inserted_count = ROW_COUNT;
  SELECT parameter_hash INTO saved_hash FROM operation_sample
    WHERE actor_id = 'A' AND operation_id = 'op-1';
  IF inserted_count <> 0 OR saved_hash <> 'hash-1' THEN
    RAISE EXCEPTION 'conflict should preserve original parameters';
  END IF;
  RAISE NOTICE 'PASS 5: ON CONFLICT preserved original operation; application must reject mismatched parameters';
END $$;

CREATE TEMP TABLE source_sample(project_id text PRIMARY KEY, amount numeric(18,2));
CREATE TEMP TABLE target_sample(LIKE source_sample INCLUDING ALL);
INSERT INTO source_sample VALUES ('P01', 770000), ('P02', 490000);
INSERT INTO target_sample VALUES ('P01', 769900), ('P02', 490100);
DO $$ DECLARE differences integer; BEGIN
  IF (SELECT sum(amount) FROM source_sample) <> (SELECT sum(amount) FROM target_sample) THEN
    RAISE EXCEPTION 'fixture needs equal grand totals';
  END IF;
  SELECT count(*) INTO differences
    FROM source_sample s FULL JOIN target_sample t USING (project_id)
    WHERE s.project_id IS NULL OR t.project_id IS NULL OR s.amount IS DISTINCT FROM t.amount;
  IF differences <> 2 THEN RAISE EXCEPTION 'expected two project differences'; END IF;
  RAISE NOTICE 'PASS 6: equal row counts and grand totals concealed two project-level errors';
END $$;

-- Deliberately verify failed-transaction semantics at top level (not a DO subtransaction).
BEGIN;
\set ON_ERROR_STOP off
INSERT INTO operation_sample VALUES ('A', 'op-1', 'hash-1');
\set duplicate_state :SQLSTATE
SELECT count(*) FROM operation_sample;
\set aborted_state :SQLSTATE
ROLLBACK;
\set ON_ERROR_STOP on
SELECT 1 / CASE WHEN :'duplicate_state' = '23505' AND :'aborted_state' = '25P02'
  THEN 1 ELSE 0 END AS failed_transaction_check;
\echo PASS 7: duplicate SQLSTATE=:duplicate_state subsequent query SQLSTATE=:aborted_state; rollback restored transaction usability
SELECT count(*) AS surviving_operations FROM operation_sample;
\echo PASS: 7 PostgreSQL semantic cases; two preceding ERROR lines are intentional and SQLSTATE-checked.
