package dev.learning;

import java.nio.file.Path;
import java.sql.*;
import java.util.Map;

/** H2/JDBC 局部实验，不代表 PostgreSQL 或真实导出 Worker 已集成。 */
public final class ExportStore {
  private final String url;

  public ExportStore(Path file) throws SQLException {
    url = "jdbc:h2:file:" + file.toAbsolutePath() + ";LOCK_TIMEOUT=15000";
    try (var db = open();
        var sql = db.createStatement()) {
      sql.execute(
          "CREATE TABLE IF NOT EXISTS export_task(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, actor VARCHAR NOT NULL, operation_id VARCHAR NOT NULL, payload_hash VARCHAR NOT NULL, status VARCHAR DEFAULT 'QUEUED', token BIGINT DEFAULT 0, file_key VARCHAR, UNIQUE(actor,operation_id))");
    }
  }

  public Connection open() throws SQLException {
    return DriverManager.getConnection(url);
  }

  public long create(String actor, String operation, Map<String, String> payload)
      throws SQLException {
    String hash = BudgetMath.digest(payload);
    try (var db = open()) {
      // 唯一约束决定胜者。重复插入单独结束，不让失败事务吞掉后续查询。
      try (var insert =
          db.prepareStatement(
              "INSERT INTO export_task(actor,operation_id,payload_hash) VALUES(?,?,?)")) {
        insert.setString(1, actor);
        insert.setString(2, operation);
        insert.setString(3, hash);
        insert.executeUpdate();
      } catch (SQLException e) {
        if (!"23505".equals(e.getSQLState())) throw e;
      }
      try (var query =
          db.prepareStatement(
              "SELECT id,payload_hash FROM export_task WHERE actor=? AND operation_id=?")) {
        query.setString(1, actor);
        query.setString(2, operation);
        try (var r = query.executeQuery()) {
          if (!r.next()) throw new SQLException("TASK_NOT_FOUND");
          if (!hash.equals(r.getString(2)))
            throw new IllegalArgumentException("IDEMPOTENCY_CONFLICT");
          return r.getLong(1);
        }
      }
    }
  }

  public int count() throws SQLException {
    try (var db = open();
        var q = db.createStatement();
        var r = q.executeQuery("SELECT COUNT(*) FROM export_task")) {
      r.next();
      return r.getInt(1);
    }
  }

  public void claim(long id, long token) throws SQLException {
    try (var db = open();
        var q =
            db.prepareStatement("UPDATE export_task SET status='RUNNING', token=? WHERE id=?")) {
      q.setLong(1, token);
      q.setLong(2, id);
      q.executeUpdate();
    }
  }

  public boolean publish(long id, long token, String key) throws SQLException {
    try (var db = open();
        var q =
            db.prepareStatement(
                "UPDATE export_task SET status='SUCCEEDED',file_key=? WHERE id=? AND token=? AND status='RUNNING'")) {
      q.setString(1, key);
      q.setLong(2, id);
      q.setLong(3, token);
      return q.executeUpdate() == 1;
    }
  }
}
